export default {
    PRIMARY_COLOR: '#4BE1D7',
    SECONDARY_COLOR: '#2A2E2E',
    DARK_COLOR: '#141414',
    GREY_COLOR: '#383E3E',
    PLACEHOLDER_COLOR: '#ACACAC',
    TEXT_COLOR: '#FFFFFF',
    TEXT_GREY_COLOR: '#B9B9B9'
};